filegroup(
  name = "model_1",
  srcs = [
    "models/model_1/graph.pb",
    "models/model_1/graph.onnx",
    "models/model_1/graph_meta.json",
    "models/model_1/samples.dat",
  ],
  visibility = ["//visibility:public"],
)
