filegroup(
  name = "model_1",
  srcs = [
    "models/model_1/2/graph.pb",
    "models/model_1/2/graph.onnx",
    "models/model_1/2/samples.dat",
    "models/model_1/model_conf.json",
  ],
  visibility = ["//visibility:public"],
)
